/**
 * Configuración de iconos heroicons para @ng-icons
 * Importamos y registramos los componentes con sus nombres exactos
 */

// Outline icons
import { 
    heroBars3,
    heroBell,
    heroBookmark,
    heroBuildingOffice,
    heroBuildingStorefront,
    heroCalendar,
    heroChartBar,
    heroChartPie,
    heroChatBubbleBottomCenterText,
    heroChatBubbleLeftRight,
    heroCheck,
    heroCheckCircle,
    heroClipboardDocumentList,
    heroClock,
    heroCog6Tooth,
    heroCog8Tooth,
    heroCreditCard,
    heroCurrencyDollar,
    heroDocument,
    heroDocumentChartBar,
    heroEllipsisHorizontalCircle,
    heroExclamationCircle,
    heroExclamationTriangle,
    heroHome,
    heroInbox,
    heroListBullet,
    heroMagnifyingGlass,
    heroMap,
    heroPaperAirplane,
    heroPlus,
    heroRectangleGroup,
    heroSquaresPlus,
    heroStar,
    heroTrash,
    heroUserCircle,
    heroUsers,
    heroXMark,
    heroArrowRightOnRectangle,
    heroArrowsRightLeft,
    heroArrowsPointingOut
} from '@ng-icons/heroicons/outline';

// Solid icons
import {
    heroArrowPathSolid,
    heroArrowsRightLeftSolid,
    heroBoltSolid,
    heroCheckCircleSolid,
    heroChevronRightSolid,
    heroCog8ToothSolid,
    heroCreditCardSolid,
    heroCurrencyDollarSolid,
    heroEnvelopeSolid,
    heroEnvelopeOpenSolid,
    heroExclamationTriangleSolid,
    heroEyeSolid,
    heroEyeSlashSolid,
    heroGlobeAltSolid,
    heroInformationCircleSolid,
    heroMoonSolid,
    heroPencilSolid,
    heroPencilSquareSolid,
    heroPlusCircleSolid,
    heroQuestionMarkCircleSolid,
    heroStarSolid,
    heroSunSolid,
    heroTruckSolid,
    heroUserCircleSolid,
    heroXCircleSolid,
    heroXMarkSolid
} from '@ng-icons/heroicons/solid';

// Mini icons
import { heroArrowLongRightMini } from '@ng-icons/heroicons/mini';

/**
 * Registro de iconos usando los nombres exactos de los componentes
 */
export const heroiconsConfig = {
    // Outline icons
    heroBars3,
    heroBell,
    heroBookmark,
    heroBuildingOffice,
    heroBuildingStorefront,
    heroCalendar,
    heroChartBar,
    heroChartPie,
    heroChatBubbleBottomCenterText,
    heroChatBubbleLeftRight,
    heroCheck,
    heroCheckCircle,
    heroClipboardDocumentList,
    heroClock,
    heroCog6Tooth,
    heroCog8Tooth,
    heroCreditCard,
    heroCurrencyDollar,
    heroDocument,
    heroDocumentChartBar,
    heroEllipsisHorizontalCircle,
    heroExclamationCircle,
    heroExclamationTriangle,
    heroHome,
    heroInbox,
    heroListBullet,
    heroMagnifyingGlass,
    heroMap,
    heroPaperAirplane,
    heroPlus,
    heroRectangleGroup,
    heroSquaresPlus,
    heroStar,
    heroTrash,
    heroUserCircle,
    heroUsers,
    heroXMark,
    heroArrowRightOnRectangle,
    heroArrowsRightLeft,
    heroArrowsPointingOut,
    
    // Solid icons
    heroArrowPathSolid,
    heroArrowsRightLeftSolid,
    heroBoltSolid,
    heroCheckCircleSolid,
    heroChevronRightSolid,
    heroCog8ToothSolid,
    heroCreditCardSolid,
    heroCurrencyDollarSolid,
    heroEnvelopeSolid,
    heroEnvelopeOpenSolid,
    heroExclamationTriangleSolid,
    heroEyeSolid,
    heroEyeSlashSolid,
    heroGlobeAltSolid,
    heroInformationCircleSolid,
    heroMoonSolid,
    heroPencilSolid,
    heroPencilSquareSolid,
    heroPlusCircleSolid,
    heroQuestionMarkCircleSolid,
    heroStarSolid,
    heroSunSolid,
    heroTruckSolid,
    heroUserCircleSolid,
    heroXCircleSolid,
    heroXMarkSolid,
    
    // Mini icons
    heroArrowLongRightMini,
};
